"""empty message

Revision ID: 12efc22e73d5
Revises: b5353fa8b384
Create Date: 2023-02-13 18:21:06.856883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12efc22e73d5'
down_revision = 'b5353fa8b384'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cloud_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_column('cloud_id')

    # ### end Alembic commands ###
