"""empty message

Revision ID: b0328ba91bb9
Revises: e6af8a4c93b7
Create Date: 2023-03-05 20:27:05.028378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0328ba91bb9'
down_revision = 'e6af8a4c93b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_column('alt')
        batch_op.drop_column('caption')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caption', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('alt', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
